# Generated by Django 4.1 on 2022-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGAPI_rest', '0007_alter_disciplina_qtd_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='qtd_horas',
            field=models.PositiveIntegerField(),
        ),
    ]
